services:

  db:
    image: postgres:16-alpine
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"

  bot:
    build:
      context: .
      dockerfile: docker/bot.Dockerfile
      target: prod
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - "./app:/opt/app/app"

volumes:
  pg_data:
