services:
  bot:
    build:
      context: .
      dockerfile: docker/bot.Dockerfile
      target: prod
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db
      - redis
    volumes:
      - "./app:/opt/app/app"
